#ifndef __FIRESTORE_CONFIG_H__
#define __FIRESTORE_CONFIG_H__

#define FIRESTORE_FIREBASE_PROJECT_ID            "TYPE_YOUR_FIREBASE_PROJECT_ID_HERE"
#define FIRESTORE_FIREBASE_API_KEY               "TYPE_YOUR_FIREBASE_API_KEY_HERE"

#endif /* __FIRESTORE_CONFIG_H__ */